In [4]:
import numpy as np

a=np.arange(15).reshape(3,5)

a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
import numpy as np

a=np.arange(15)

a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
import numpy as np

a = np.arange(10,60,5).reshape(2,5)

a

array([[10, 15, 20, 25, 30],
       [35, 40, 45, 50, 55]])

In [19]:
import numpy as np

print(np.array([[2,4,5],[1,6,3]]))

[[2 4 5]
 [1 6 3]]


In [24]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a[0,1]),(a[1,2])
print(a[0])

[[1 2 3]
 [4 5 6]]
2
[1 2 3]


In [25]:
a=np.array([[3,-1,4],[1,5,9]])
b=np.array([[2,4,-5,6],[-1,7,9,3],[3,2,-7,-2]])

np.dot(a,b)

array([[ 19,  13, -52,   7],
       [ 24,  57, -23,   3]])

In [28]:
print([1,2,3],[4,5,6])

print([1,2,3]*4)

[1, 2, 3] [4, 5, 6]
[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


In [9]:
import numpy as np
x=np.array([3,-4,1])
y=np.array([5,2,3])
x+10

array([13,  6, 11])

In [20]:
x=np.arange(0,50,10)
index= np.array([3,1,4])
print(x[index])
mask=np.array([True,False,False,True,False])
print(x[mask])

[30 10 40]
[ 0 30]


In [21]:
y=np.arange(10,20,2)
print(y)
mask=y>15
print(mask)
print(y[mask])
y[mask] = 100
print(y)

[10 12 14 16 18]
[False False False  True  True]
[16 18]
[ 10  12  14 100 100]


In [27]:
import numpy as np
iris_data = np.genfromtxt(r'D:\\python\\Lib\\site-packages\\sklearn\\datasets\\data\\iris.csv',
                          delimiter=",", )
print(iris_data)

OSError: D:\\python\\Lib\\site-packages\\sklearn\\datasets\\data\\iris.csv not found.